export const POSTS_FETCH_REQUESTED = "POSTS/POSTS_FETCH_REQUESTED";
export const POSTS_FETCH_SUCCEEDED = "POSTS/POSTS_FETCH_SUCCEEDED";
export const POSTS_FETCH_FAILED = "POSTS/POSTS_FETCH_FAILED";

export const POST_ADD = "POSTS/POST_ADD";
export const POST_EDIT = "POSTS/POST_EDIT";
export const POST_REMOVE = "POSTS/POST_REMOVE";

export const fetchAllPosts = () => ({
  type: POSTS_FETCH_REQUESTED
});
